---
project_name: kubectl-chart
builds:
  - main: ./cmd/main.go
    binary: kubectl-chart
    ldflags:
      - -s -w
        -X github.com/martinohmann/kubectl-chart/pkg/version.gitVersion={{.Version}}
        -X github.com/martinohmann/kubectl-chart/pkg/version.gitCommit={{.FullCommit}}
        -X github.com/martinohmann/kubectl-chart/pkg/version.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - format: binary
    files:
      - none*
    replacements:
      386: i386
      amd64: x86_64
release:
  github:
    owner: martinohmann
    name: kubectl-chart
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
